services:
  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    container_name: llmoxy
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    env_file:
      - .env
    command:
      - "--config=/app/config.yaml"
      - "--port=4000" 
      - "--host=0.0.0.0"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 http://localhost:4000/health/liveliness || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s